# This is a basic workflow to help you get started with Actions

name: Publish

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  # This concurrency group ensures that only one workflow run for this workflow
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - uses: actions/checkout@v4

      - name: Build using Podman
        run: |-
          make docker-html

          mkdir -p build/html && tar -xf build/docker-html.tar -C build/html

      - name: Bundle and upload
        uses: actions/upload-artifact@v4
        with:
          name: docker-html
          path: ./build/docker-html.tar
        # Sets the output variable `artifact-id`

  deploy:
    # See: https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-html

      - name: Untar files for upload
        run: tar xf docker-html.tar --strip-components=1

      - name: Configure Github Pages
        uses: actions/configure-pages@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload GH Pages files
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
